// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"pkg.berachain.dev/jinx/eth/core"
	"pkg.berachain.dev/jinx/eth/core/precompile"
	"sync"
)

// Ensure, that JinxHostChainMock does implement core.JinxHostChain.
// If this is not the case, regenerate this file with moq.
var _ core.JinxHostChain = &JinxHostChainMock{}

// JinxHostChainMock is a mock implementation of core.JinxHostChain.
//
//	func TestSomethingThatUsesJinxHostChain(t *testing.T) {
//
//		// make and configure a mocked core.JinxHostChain
//		mockedJinxHostChain := &JinxHostChainMock{
//			GetBlockPluginFunc: func() core.BlockPlugin {
//				panic("mock out the GetBlockPlugin method")
//			},
//			GetConfigurationPluginFunc: func() core.ConfigurationPlugin {
//				panic("mock out the GetConfigurationPlugin method")
//			},
//			GetGasPluginFunc: func() core.GasPlugin {
//				panic("mock out the GetGasPlugin method")
//			},
//			GetHistoricalPluginFunc: func() core.HistoricalPlugin {
//				panic("mock out the GetHistoricalPlugin method")
//			},
//			GetPrecompilePluginFunc: func() precompile.Plugin {
//				panic("mock out the GetPrecompilePlugin method")
//			},
//			GetStatePluginFunc: func() core.StatePlugin {
//				panic("mock out the GetStatePlugin method")
//			},
//			GetTxPoolPluginFunc: func() core.TxPoolPlugin {
//				panic("mock out the GetTxPoolPlugin method")
//			},
//		}
//
//		// use mockedJinxHostChain in code that requires core.JinxHostChain
//		// and then make assertions.
//
//	}
type JinxHostChainMock struct {
	// GetBlockPluginFunc mocks the GetBlockPlugin method.
	GetBlockPluginFunc func() core.BlockPlugin

	// GetConfigurationPluginFunc mocks the GetConfigurationPlugin method.
	GetConfigurationPluginFunc func() core.ConfigurationPlugin

	// GetGasPluginFunc mocks the GetGasPlugin method.
	GetGasPluginFunc func() core.GasPlugin

	// GetHistoricalPluginFunc mocks the GetHistoricalPlugin method.
	GetHistoricalPluginFunc func() core.HistoricalPlugin

	// GetPrecompilePluginFunc mocks the GetPrecompilePlugin method.
	GetPrecompilePluginFunc func() precompile.Plugin

	// GetStatePluginFunc mocks the GetStatePlugin method.
	GetStatePluginFunc func() core.StatePlugin

	// GetTxPoolPluginFunc mocks the GetTxPoolPlugin method.
	GetTxPoolPluginFunc func() core.TxPoolPlugin

	// calls tracks calls to the methods.
	calls struct {
		// GetBlockPlugin holds details about calls to the GetBlockPlugin method.
		GetBlockPlugin []struct {
		}
		// GetConfigurationPlugin holds details about calls to the GetConfigurationPlugin method.
		GetConfigurationPlugin []struct {
		}
		// GetGasPlugin holds details about calls to the GetGasPlugin method.
		GetGasPlugin []struct {
		}
		// GetHistoricalPlugin holds details about calls to the GetHistoricalPlugin method.
		GetHistoricalPlugin []struct {
		}
		// GetPrecompilePlugin holds details about calls to the GetPrecompilePlugin method.
		GetPrecompilePlugin []struct {
		}
		// GetStatePlugin holds details about calls to the GetStatePlugin method.
		GetStatePlugin []struct {
		}
		// GetTxPoolPlugin holds details about calls to the GetTxPoolPlugin method.
		GetTxPoolPlugin []struct {
		}
	}
	lockGetBlockPlugin         sync.RWMutex
	lockGetConfigurationPlugin sync.RWMutex
	lockGetGasPlugin           sync.RWMutex
	lockGetHistoricalPlugin    sync.RWMutex
	lockGetPrecompilePlugin    sync.RWMutex
	lockGetStatePlugin         sync.RWMutex
	lockGetTxPoolPlugin        sync.RWMutex
}

// GetBlockPlugin calls GetBlockPluginFunc.
func (mock *JinxHostChainMock) GetBlockPlugin() core.BlockPlugin {
	if mock.GetBlockPluginFunc == nil {
		panic("JinxHostChainMock.GetBlockPluginFunc: method is nil but JinxHostChain.GetBlockPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetBlockPlugin.Lock()
	mock.calls.GetBlockPlugin = append(mock.calls.GetBlockPlugin, callInfo)
	mock.lockGetBlockPlugin.Unlock()
	return mock.GetBlockPluginFunc()
}

// GetBlockPluginCalls gets all the calls that were made to GetBlockPlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetBlockPluginCalls())
func (mock *JinxHostChainMock) GetBlockPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetBlockPlugin.RLock()
	calls = mock.calls.GetBlockPlugin
	mock.lockGetBlockPlugin.RUnlock()
	return calls
}

// GetConfigurationPlugin calls GetConfigurationPluginFunc.
func (mock *JinxHostChainMock) GetConfigurationPlugin() core.ConfigurationPlugin {
	if mock.GetConfigurationPluginFunc == nil {
		panic("JinxHostChainMock.GetConfigurationPluginFunc: method is nil but JinxHostChain.GetConfigurationPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfigurationPlugin.Lock()
	mock.calls.GetConfigurationPlugin = append(mock.calls.GetConfigurationPlugin, callInfo)
	mock.lockGetConfigurationPlugin.Unlock()
	return mock.GetConfigurationPluginFunc()
}

// GetConfigurationPluginCalls gets all the calls that were made to GetConfigurationPlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetConfigurationPluginCalls())
func (mock *JinxHostChainMock) GetConfigurationPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfigurationPlugin.RLock()
	calls = mock.calls.GetConfigurationPlugin
	mock.lockGetConfigurationPlugin.RUnlock()
	return calls
}

// GetGasPlugin calls GetGasPluginFunc.
func (mock *JinxHostChainMock) GetGasPlugin() core.GasPlugin {
	if mock.GetGasPluginFunc == nil {
		panic("JinxHostChainMock.GetGasPluginFunc: method is nil but JinxHostChain.GetGasPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetGasPlugin.Lock()
	mock.calls.GetGasPlugin = append(mock.calls.GetGasPlugin, callInfo)
	mock.lockGetGasPlugin.Unlock()
	return mock.GetGasPluginFunc()
}

// GetGasPluginCalls gets all the calls that were made to GetGasPlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetGasPluginCalls())
func (mock *JinxHostChainMock) GetGasPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetGasPlugin.RLock()
	calls = mock.calls.GetGasPlugin
	mock.lockGetGasPlugin.RUnlock()
	return calls
}

// GetHistoricalPlugin calls GetHistoricalPluginFunc.
func (mock *JinxHostChainMock) GetHistoricalPlugin() core.HistoricalPlugin {
	if mock.GetHistoricalPluginFunc == nil {
		panic("JinxHostChainMock.GetHistoricalPluginFunc: method is nil but JinxHostChain.GetHistoricalPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHistoricalPlugin.Lock()
	mock.calls.GetHistoricalPlugin = append(mock.calls.GetHistoricalPlugin, callInfo)
	mock.lockGetHistoricalPlugin.Unlock()
	return mock.GetHistoricalPluginFunc()
}

// GetHistoricalPluginCalls gets all the calls that were made to GetHistoricalPlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetHistoricalPluginCalls())
func (mock *JinxHostChainMock) GetHistoricalPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHistoricalPlugin.RLock()
	calls = mock.calls.GetHistoricalPlugin
	mock.lockGetHistoricalPlugin.RUnlock()
	return calls
}

// GetPrecompilePlugin calls GetPrecompilePluginFunc.
func (mock *JinxHostChainMock) GetPrecompilePlugin() precompile.Plugin {
	if mock.GetPrecompilePluginFunc == nil {
		panic("JinxHostChainMock.GetPrecompilePluginFunc: method is nil but JinxHostChain.GetPrecompilePlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPrecompilePlugin.Lock()
	mock.calls.GetPrecompilePlugin = append(mock.calls.GetPrecompilePlugin, callInfo)
	mock.lockGetPrecompilePlugin.Unlock()
	return mock.GetPrecompilePluginFunc()
}

// GetPrecompilePluginCalls gets all the calls that were made to GetPrecompilePlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetPrecompilePluginCalls())
func (mock *JinxHostChainMock) GetPrecompilePluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPrecompilePlugin.RLock()
	calls = mock.calls.GetPrecompilePlugin
	mock.lockGetPrecompilePlugin.RUnlock()
	return calls
}

// GetStatePlugin calls GetStatePluginFunc.
func (mock *JinxHostChainMock) GetStatePlugin() core.StatePlugin {
	if mock.GetStatePluginFunc == nil {
		panic("JinxHostChainMock.GetStatePluginFunc: method is nil but JinxHostChain.GetStatePlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetStatePlugin.Lock()
	mock.calls.GetStatePlugin = append(mock.calls.GetStatePlugin, callInfo)
	mock.lockGetStatePlugin.Unlock()
	return mock.GetStatePluginFunc()
}

// GetStatePluginCalls gets all the calls that were made to GetStatePlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetStatePluginCalls())
func (mock *JinxHostChainMock) GetStatePluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetStatePlugin.RLock()
	calls = mock.calls.GetStatePlugin
	mock.lockGetStatePlugin.RUnlock()
	return calls
}

// GetTxPoolPlugin calls GetTxPoolPluginFunc.
func (mock *JinxHostChainMock) GetTxPoolPlugin() core.TxPoolPlugin {
	if mock.GetTxPoolPluginFunc == nil {
		panic("JinxHostChainMock.GetTxPoolPluginFunc: method is nil but JinxHostChain.GetTxPoolPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTxPoolPlugin.Lock()
	mock.calls.GetTxPoolPlugin = append(mock.calls.GetTxPoolPlugin, callInfo)
	mock.lockGetTxPoolPlugin.Unlock()
	return mock.GetTxPoolPluginFunc()
}

// GetTxPoolPluginCalls gets all the calls that were made to GetTxPoolPlugin.
// Check the length with:
//
//	len(mockedJinxHostChain.GetTxPoolPluginCalls())
func (mock *JinxHostChainMock) GetTxPoolPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTxPoolPlugin.RLock()
	calls = mock.calls.GetTxPoolPlugin
	mock.lockGetTxPoolPlugin.RUnlock()
	return calls
}
